# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
    ]
