# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170127_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(default=b'', editable=False, max_length=1000),
        ),
    ]
