# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_customuser_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(default='', editable=False, max_length=1000),
        ),
    ]
