# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='status',
            new_name='state',
        ),
    ]
