from django.db import models

from server.models import Server


class Service(models.Model):
    """
    Service model class

    Attributes:
        id (int): autogenerated primary key
        name (str): service name
        status (str): service status
        server (int): foreign key to server which owns service (many-to-one)

    """

    name = models.CharField(default="", max_length=200)
    status = models.CharField(default="", max_length=50)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)

    def __str__(self):
        return "Service id: {}, name: {}, status: {}".format(self.id,
                                                             self.name,
                                                             self.status)
