# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=20)),
                ('check_plugin_name', models.CharField(max_length=20)),
                ('check_run_freq', models.IntegerField()),
            ],
        ),
    ]
