# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:26
from __future__ import unicode_literals

from django.db import migrations


PLUGINS = [
    {
        'name': 'check_dns',
        'template': '/usr/lib/nagios/plugins/check_dns -H {host}',
    },
    {
        'name': 'check_ftp',
        'template': '/usr/lib/nagios/plugins/check_ftp -H {host} -p {port}',
    },
    {
        'name': 'check_http',
        'template': '/usr/lib/nagios/plugins/check_http -H {host} -p {port}',
    },
    {
        'name': 'check_ping',
        'template': '/usr/lib/nagios/plugins/check_ping -H {host} -w 100.0,20% -c 500.0,60%',
    },
    {
        'name': 'check_smtp',
        'template': '/usr/lib/nagios/plugins/check_smtp -H {host} -p {port}',
    },
    {
        'name': 'check_tcp',
        'template': '/usr/lib/nagios/plugins/check_tcp -H {host} -p {port}',
    },
    {
        'name': 'check_time',
        'template': '/usr/lib/nagios/plugins/check_time -H {host} -p {port}',
    },
]


def add_plugins(apps, schema_editor):
    """Add chosen plugin names into database."""

    NagPlugin = apps.get_model('nagplugin', 'NagPlugin')

    for plugin_info in PLUGINS:
        plugin = NagPlugin(**plugin_info)
        plugin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nagplugin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_plugins),
    ]
