# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagplugin', '0002_auto_20170205_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagplugin',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
