from django.db import models


class NagPlugin(models.Model):
    """Nagios plugin model.

    Attributes:
        id (int): autogenerated primary key.
        name (str): plugin name.
        template(str): template to run plugin.
    """

    name = models.CharField(default='', max_length=200)
    template = models.CharField(default='', max_length=255)

    @staticmethod
    def get_by_id(id):
        """Get nagios plugin with given id.

        Args:
            id (int): plugin id.

        Returns:
            NagPlugin: If plugin was found, and None otherwise.
        """

        try:
            plugin = NagPlugin.objects.get(id=id)
        except Exception as error:
            return None

        return plugin

    @staticmethod
    def get_by_name(name):
        """Get nagios plugins with given name.

        Args:
            name(str): plugin name.

        Returns:
            QuerySet<Service>: QuerySet of nagios plugins.
        """

        plugins = NagPlugin.objects.filter(name=name)

        return plugins

    @staticmethod
    def get(start=0, end=20):
        """Get nagios plugins.

        The slice is returned from start index to end.

        Args:
            start(int, optional): start position when getting all plugins. Defaults to 0.
            end(int, optional): end position when getting all plugins. Defaults to 20.

        Returns:
            QuerySet<Service>: QuerySet of nagios plugins.
        """

        plugins = NagPlugin.objects.all()[start:end]

        return plugins

    def to_dict(self):
        """Convert model object to dictionary.

        Return:
            dict:
                {
                    'id': id,
                    'name': name,
                    'template': template
                }
        """

        return {
            'id': self.id,
            'name': self.name,
            'template': self.template,
        }

    def __str__(self):
        return 'Plugin id: {}, name: {}, template: {}'.format(self.id, self.name, self.template)
