# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
