# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
        ('service', '0002_auto_20170119_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='server.Server'),
            preserve_default=False,
        ),
    ]
