# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170202_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
