# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=20)),
                ('plugin_name', models.CharField(default=0, max_length=20)),
                ('run_freq', models.IntegerField(default=0)),
            ],
        ),
    ]
