# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_check_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='target_port',
            field=models.IntegerField(default=0),
        ),
    ]
