# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagplugin', '0002_auto_20170205_1526'),
        ('check', '0003_check_target_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='plugin_name',
        ),
        migrations.AddField(
            model_name='check',
            name='plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nagplugin.NagPlugin'),
            preserve_default=False,
        ),
    ]
