# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20170211_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='output',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
