# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20170218_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
